# Generated by Django 4.0 on 2022-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indiansav_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('message', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=256)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=256)),
                ('message', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('ratings', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
